version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
    mysql:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: basicbug_db
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
        secrets:
            - mysql_secret
        ports:
            - "3306:3306"

    redis:
        image: redis:6.0.5-alpine
        ports:
            - "6379:6379"

secrets:
    mysql_secret:
        file: config/dev/basicbug_mysql_password

volumes:
    db_data:
