version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
    mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - db_data:/var/lib/mysql
            - ./utf8.cnf:/etc/mysql/my.cnf
            - ./utf8.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            MYSQL_DATABASE: basicbug_db
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
        secrets:
            - mysql_secret
        ports:
            - "3306:3306"

    redis:
        image: redis:6.0.5-alpine
        network_mode: host
        ports:
            - "6379:6379"
        command: redis-server /data/redis.conf

secrets:
    mysql_secret:
        file: config/dev/basicbug_mysql_password

volumes:
    db_data:
