spring:
    jwt:
        secret: ${JWT_SECRET}

    social:
        naver:
            client_id: ${NAVER_CLIENT_ID}
            client_secret: ${NAVER_CLIENT_SECRET}
            redirect: /social/login/naver
            url:
                login: https://nid.naver.com/oauth2.0/authorize
                token: https://nid.naver.com/oauth2.0/token
                profile: https://openapi.naver.com/v1/nid/me
    url:
        base: http://localhost:8080