spring:
    jwt:
        secret: ${JWT_SECRET}

    social:
        naver:
            client_id: ${NAVER_CLIENT_ID}
            client_secret: ${NAVER_CLIENT_SECRET}
            redirect: /v1/social/login/naver
            url:
                login: https://nid.naver.com/oauth2.0/authorize
                token: https://nid.naver.com/oauth2.0/token
                profile: https://openapi.naver.com/v1/nid/me
    url:
        base: http://localhost:8080

    datasource:
        url: jdbc:mysql://localhost:3306/basicbug_db?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
        username: ${DB_USER_NAME}
        password: ${DB_USER_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always
        sql-script-encoding: UTF-8